# Generated by Django 5.1.7 on 2025-03-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='data_evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='inscricao_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='inscricao_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='link_inscricao',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('seminario', 'Seminário'), ('congresso', 'Congresso'), ('olimpiada', 'Olimpíada'), ('feira', 'Feira'), ('festival', 'Festival'), ('exposicao', 'Exposição'), ('encontro', 'Encontro'), ('curso', 'Curso'), ('treinamento', 'Treinamento'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
