# Generated by Django 5.1.7 on 2025-03-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_evento_data_evento_evento_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='link_maps',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='nome_local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
