# Generated by Django 5.1.7 on 2025-03-17 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_link_maps_evento_nome_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('local', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('alimentacao', 'Alimentação'), ('apresentacao_artistica', 'Apresentação Artística'), ('apresentacao_trabalho_cientifico', 'Apresentação de Trabalho Científico'), ('cerimonia', 'Cerimônia'), ('coloquio', 'Colóquio'), ('conferencia', 'Conferência'), ('curso', 'Curso'), ('divulgacao', 'Divulgação'), ('encontro', 'Encontro'), ('espetaculo', 'Espetáculo')], max_length=50)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='eventos.evento')),
            ],
        ),
    ]
