# Generated by Django 5.1.7 on 2025-03-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='limite_vagas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
