# Generated by Django 5.1.7 on 2025-03-19 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_atividade_limite_vagas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='inscritos',
            field=models.ManyToManyField(blank=True, related_name='atividades_inscritas', to=settings.AUTH_USER_MODEL),
        ),
    ]
